//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionSIM.ServiceFacturaComputarizadaStandar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", ConfigurationName="ServiceFacturaComputarizadaStandar.FacturacionEstandarController")]
    public interface FacturacionEstandarController {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nAnulacionFacturaComputariazadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nAnulacionFacturaComputariazadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaResponse validacionAnulacionFacturaComputariazada(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nAnulacionFacturaComputariazadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nAnulacionFacturaComputariazadaResponse")]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaResponse> validacionAnulacionFacturaComputariazadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "PaqueteFacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "PaqueteFacturaComputarizadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaResponse recepcionPaqueteFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "PaqueteFacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "PaqueteFacturaComputarizadaResponse")]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaResponse> recepcionPaqueteFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionFacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionFacturaComputarizadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaResponse validacionRecepcionFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionFacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionFacturaComputarizadaResponse")]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaResponse> validacionRecepcionFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionPaqueteFacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionPaqueteFacturaComputarizadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaResponse validacionRecepcionPaqueteFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionPaqueteFacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/validacio" +
            "nRecepcionPaqueteFacturaComputarizadaResponse")]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaResponse> validacionRecepcionPaqueteFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/anulacion" +
            "FacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/anulacion" +
            "FacturaComputarizadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaResponse anulacionFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/anulacion" +
            "FacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/anulacion" +
            "FacturaComputarizadaResponse")]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaResponse> anulacionFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/verificar" +
            "ConexionRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/verificar" +
            "ConexionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionResponse verificarConexion(FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/verificar" +
            "ConexionRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/verificar" +
            "ConexionResponse")]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionResponse> verificarConexionAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "FacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "FacturaComputarizadaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaResponse recepcionFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "FacturaComputarizadaRequest", ReplyAction="http://controller.fest.fac.sre.sin.gob.bo/FacturacionEstandarController/recepcion" +
            "FacturaComputarizadaResponse")]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaResponse> recepcionFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/")]
    public partial class respuestaListaRegistroRecepcionesSoapDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private long codigoRecepcionField;
        
        private bool codigoRecepcionFieldSpecified;
        
        private System.Nullable<int>[] listaCodigosRespuestasField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified {
            get {
                return this.codigoEstadoFieldSpecified;
            }
            set {
                this.codigoEstadoFieldSpecified = value;
                this.RaisePropertyChanged("codigoEstadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoRecepcionSpecified {
            get {
                return this.codigoRecepcionFieldSpecified;
            }
            set {
                this.codigoRecepcionFieldSpecified = value;
                this.RaisePropertyChanged("codigoRecepcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaCodigosRespuestas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int>[] listaCodigosRespuestas {
            get {
                return this.listaCodigosRespuestasField;
            }
            set {
                this.listaCodigosRespuestasField = value;
                this.RaisePropertyChanged("listaCodigosRespuestas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/")]
    public partial class recepcionErrorDetalleDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codigoRecepcionIndividualField;
        
        private string cufField;
        
        private System.Nullable<int>[] listaCodigosErrorField;
        
        private long numeroFacturaField;
        
        private bool numeroFacturaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long codigoRecepcionIndividual {
            get {
                return this.codigoRecepcionIndividualField;
            }
            set {
                this.codigoRecepcionIndividualField = value;
                this.RaisePropertyChanged("codigoRecepcionIndividual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
                this.RaisePropertyChanged("cuf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaCodigosError", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int>[] listaCodigosError {
            get {
                return this.listaCodigosErrorField;
            }
            set {
                this.listaCodigosErrorField = value;
                this.RaisePropertyChanged("listaCodigosError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("numeroFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroFacturaSpecified {
            get {
                return this.numeroFacturaFieldSpecified;
            }
            set {
                this.numeroFacturaFieldSpecified = value;
                this.RaisePropertyChanged("numeroFacturaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/")]
    public partial class respuestaValidacionRecepcionPaqueteDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoEstadoField;
        
        private long codigoRecepcionField;
        
        private recepcionErrorDetalleDto[] listaErroresField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaErrores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public recepcionErrorDetalleDto[] listaErrores {
            get {
                return this.listaErroresField;
            }
            set {
                this.listaErroresField = value;
                this.RaisePropertyChanged("listaErrores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionAnulacionFacturaComputariazada", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class validacionAnulacionFacturaComputariazadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoAmbiente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cufd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoSector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoPuntoVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long pinAnulacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numeroDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long celular;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoMotivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoRecepcion;
        
        public validacionAnulacionFacturaComputariazadaRequest() {
        }
        
        public validacionAnulacionFacturaComputariazadaRequest(
                    string codigoSistema, 
                    int codigoAmbiente, 
                    long nit, 
                    string cuis, 
                    string cufd, 
                    int codigoDocumentoFiscal, 
                    int codigoDocumentoSector, 
                    int codigoSucursal, 
                    long codigoPuntoVenta, 
                    long pinAnulacion, 
                    long numeroDocumentoFiscal, 
                    string cuf, 
                    string email, 
                    long celular, 
                    int codigoMotivo, 
                    long codigoRecepcion) {
            this.codigoSistema = codigoSistema;
            this.codigoAmbiente = codigoAmbiente;
            this.nit = nit;
            this.cuis = cuis;
            this.cufd = cufd;
            this.codigoDocumentoFiscal = codigoDocumentoFiscal;
            this.codigoDocumentoSector = codigoDocumentoSector;
            this.codigoSucursal = codigoSucursal;
            this.codigoPuntoVenta = codigoPuntoVenta;
            this.pinAnulacion = pinAnulacion;
            this.numeroDocumentoFiscal = numeroDocumentoFiscal;
            this.cuf = cuf;
            this.email = email;
            this.celular = celular;
            this.codigoMotivo = codigoMotivo;
            this.codigoRecepcion = codigoRecepcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionAnulacionFacturaComputariazadaResponse", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class validacionAnulacionFacturaComputariazadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return;
        
        public validacionAnulacionFacturaComputariazadaResponse() {
        }
        
        public validacionAnulacionFacturaComputariazadaResponse(FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFacturaComputarizada", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFacturaComputarizadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoAmbiente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoModalidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cufd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoSector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoPuntoVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaEnvio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string archivo;
        
        public recepcionPaqueteFacturaComputarizadaRequest() {
        }
        
        public recepcionPaqueteFacturaComputarizadaRequest(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, string fechaEnvio, string archivo) {
            this.codigoSistema = codigoSistema;
            this.codigoAmbiente = codigoAmbiente;
            this.codigoEmision = codigoEmision;
            this.codigoModalidad = codigoModalidad;
            this.nit = nit;
            this.cuis = cuis;
            this.cufd = cufd;
            this.codigoDocumentoFiscal = codigoDocumentoFiscal;
            this.codigoDocumentoSector = codigoDocumentoSector;
            this.codigoSucursal = codigoSucursal;
            this.codigoPuntoVenta = codigoPuntoVenta;
            this.fechaEnvio = fechaEnvio;
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFacturaComputarizadaResponse", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFacturaComputarizadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return;
        
        public recepcionPaqueteFacturaComputarizadaResponse() {
        }
        
        public recepcionPaqueteFacturaComputarizadaResponse(FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionFacturaComputarizada", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionFacturaComputarizadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoAmbiente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoModalidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cufd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoSector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoPuntoVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoRecepcion;
        
        public validacionRecepcionFacturaComputarizadaRequest() {
        }
        
        public validacionRecepcionFacturaComputarizadaRequest(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long codigoRecepcion) {
            this.codigoSistema = codigoSistema;
            this.codigoAmbiente = codigoAmbiente;
            this.codigoEmision = codigoEmision;
            this.codigoModalidad = codigoModalidad;
            this.nit = nit;
            this.cuis = cuis;
            this.cufd = cufd;
            this.codigoDocumentoFiscal = codigoDocumentoFiscal;
            this.codigoDocumentoSector = codigoDocumentoSector;
            this.codigoSucursal = codigoSucursal;
            this.codigoPuntoVenta = codigoPuntoVenta;
            this.codigoRecepcion = codigoRecepcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionFacturaComputarizadaResponse", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionFacturaComputarizadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return;
        
        public validacionRecepcionFacturaComputarizadaResponse() {
        }
        
        public validacionRecepcionFacturaComputarizadaResponse(FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFacturaComputarizada", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFacturaComputarizadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoAmbiente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoModalidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cufd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoSector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoPuntoVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoRecepcion;
        
        public validacionRecepcionPaqueteFacturaComputarizadaRequest() {
        }
        
        public validacionRecepcionPaqueteFacturaComputarizadaRequest(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long codigoRecepcion) {
            this.codigoSistema = codigoSistema;
            this.codigoAmbiente = codigoAmbiente;
            this.codigoEmision = codigoEmision;
            this.codigoModalidad = codigoModalidad;
            this.nit = nit;
            this.cuis = cuis;
            this.cufd = cufd;
            this.codigoDocumentoFiscal = codigoDocumentoFiscal;
            this.codigoDocumentoSector = codigoDocumentoSector;
            this.codigoSucursal = codigoSucursal;
            this.codigoPuntoVenta = codigoPuntoVenta;
            this.codigoRecepcion = codigoRecepcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFacturaComputarizadaResponse", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFacturaComputarizadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaValidacionRecepcionPaqueteDto @return;
        
        public validacionRecepcionPaqueteFacturaComputarizadaResponse() {
        }
        
        public validacionRecepcionPaqueteFacturaComputarizadaResponse(FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaValidacionRecepcionPaqueteDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFacturaComputarizada", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class anulacionFacturaComputarizadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoAmbiente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cufd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoSector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoPuntoVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long pinAnulacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numeroDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long celular;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoMotivo;
        
        public anulacionFacturaComputarizadaRequest() {
        }
        
        public anulacionFacturaComputarizadaRequest(string codigoSistema, int codigoAmbiente, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long pinAnulacion, long numeroDocumentoFiscal, string cuf, string email, long celular, int codigoMotivo) {
            this.codigoSistema = codigoSistema;
            this.codigoAmbiente = codigoAmbiente;
            this.nit = nit;
            this.cuis = cuis;
            this.cufd = cufd;
            this.codigoDocumentoFiscal = codigoDocumentoFiscal;
            this.codigoDocumentoSector = codigoDocumentoSector;
            this.codigoSucursal = codigoSucursal;
            this.codigoPuntoVenta = codigoPuntoVenta;
            this.pinAnulacion = pinAnulacion;
            this.numeroDocumentoFiscal = numeroDocumentoFiscal;
            this.cuf = cuf;
            this.email = email;
            this.celular = celular;
            this.codigoMotivo = codigoMotivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFacturaComputarizadaResponse", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class anulacionFacturaComputarizadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return;
        
        public anulacionFacturaComputarizadaResponse() {
        }
        
        public anulacionFacturaComputarizadaResponse(FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarConexion", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class verificarConexionRequest {
        
        public verificarConexionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarConexionResponse", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class verificarConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public verificarConexionResponse() {
        }
        
        public verificarConexionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFacturaComputarizada", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class recepcionFacturaComputarizadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoAmbiente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoModalidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cufd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoFiscal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoDocumentoSector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoSucursal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long codigoPuntoVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaEnvio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string archivo;
        
        public recepcionFacturaComputarizadaRequest() {
        }
        
        public recepcionFacturaComputarizadaRequest(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, string fechaEnvio, string archivo) {
            this.codigoSistema = codigoSistema;
            this.codigoAmbiente = codigoAmbiente;
            this.codigoEmision = codigoEmision;
            this.codigoModalidad = codigoModalidad;
            this.nit = nit;
            this.cuis = cuis;
            this.cufd = cufd;
            this.codigoDocumentoFiscal = codigoDocumentoFiscal;
            this.codigoDocumentoSector = codigoDocumentoSector;
            this.codigoSucursal = codigoSucursal;
            this.codigoPuntoVenta = codigoPuntoVenta;
            this.fechaEnvio = fechaEnvio;
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFacturaComputarizadaResponse", WrapperNamespace="http://controller.fest.fac.sre.sin.gob.bo/", IsWrapped=true)]
    public partial class recepcionFacturaComputarizadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.fest.fac.sre.sin.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return;
        
        public recepcionFacturaComputarizadaResponse() {
        }
        
        public recepcionFacturaComputarizadaResponse(FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturacionEstandarControllerChannel : FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturacionEstandarControllerClient : System.ServiceModel.ClientBase<FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController>, FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController {
        
        public FacturacionEstandarControllerClient() {
        }
        
        public FacturacionEstandarControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturacionEstandarControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionEstandarControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionEstandarControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaResponse FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.validacionAnulacionFacturaComputariazada(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest request) {
            return base.Channel.validacionAnulacionFacturaComputariazada(request);
        }
        
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto validacionAnulacionFacturaComputariazada(
                    string codigoSistema, 
                    int codigoAmbiente, 
                    long nit, 
                    string cuis, 
                    string cufd, 
                    int codigoDocumentoFiscal, 
                    int codigoDocumentoSector, 
                    int codigoSucursal, 
                    long codigoPuntoVenta, 
                    long pinAnulacion, 
                    long numeroDocumentoFiscal, 
                    string cuf, 
                    string email, 
                    long celular, 
                    int codigoMotivo, 
                    long codigoRecepcion) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.pinAnulacion = pinAnulacion;
            inValue.numeroDocumentoFiscal = numeroDocumentoFiscal;
            inValue.cuf = cuf;
            inValue.email = email;
            inValue.celular = celular;
            inValue.codigoMotivo = codigoMotivo;
            inValue.codigoRecepcion = codigoRecepcion;
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaResponse retVal = ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).validacionAnulacionFacturaComputariazada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaResponse> FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.validacionAnulacionFacturaComputariazadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest request) {
            return base.Channel.validacionAnulacionFacturaComputariazadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaResponse> validacionAnulacionFacturaComputariazadaAsync(
                    string codigoSistema, 
                    int codigoAmbiente, 
                    long nit, 
                    string cuis, 
                    string cufd, 
                    int codigoDocumentoFiscal, 
                    int codigoDocumentoSector, 
                    int codigoSucursal, 
                    long codigoPuntoVenta, 
                    long pinAnulacion, 
                    long numeroDocumentoFiscal, 
                    string cuf, 
                    string email, 
                    long celular, 
                    int codigoMotivo, 
                    long codigoRecepcion) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionAnulacionFacturaComputariazadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.pinAnulacion = pinAnulacion;
            inValue.numeroDocumentoFiscal = numeroDocumentoFiscal;
            inValue.cuf = cuf;
            inValue.email = email;
            inValue.celular = celular;
            inValue.codigoMotivo = codigoMotivo;
            inValue.codigoRecepcion = codigoRecepcion;
            return ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).validacionAnulacionFacturaComputariazadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaResponse FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.recepcionPaqueteFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest request) {
            return base.Channel.recepcionPaqueteFacturaComputarizada(request);
        }
        
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto recepcionPaqueteFacturaComputarizada(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, string fechaEnvio, string archivo) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.fechaEnvio = fechaEnvio;
            inValue.archivo = archivo;
            FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaResponse retVal = ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).recepcionPaqueteFacturaComputarizada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaResponse> FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.recepcionPaqueteFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest request) {
            return base.Channel.recepcionPaqueteFacturaComputarizadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaResponse> recepcionPaqueteFacturaComputarizadaAsync(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, string fechaEnvio, string archivo) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionPaqueteFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.fechaEnvio = fechaEnvio;
            inValue.archivo = archivo;
            return ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).recepcionPaqueteFacturaComputarizadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaResponse FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.validacionRecepcionFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest request) {
            return base.Channel.validacionRecepcionFacturaComputarizada(request);
        }
        
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto validacionRecepcionFacturaComputarizada(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long codigoRecepcion) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.codigoRecepcion = codigoRecepcion;
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaResponse retVal = ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).validacionRecepcionFacturaComputarizada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaResponse> FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.validacionRecepcionFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest request) {
            return base.Channel.validacionRecepcionFacturaComputarizadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaResponse> validacionRecepcionFacturaComputarizadaAsync(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long codigoRecepcion) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.codigoRecepcion = codigoRecepcion;
            return ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).validacionRecepcionFacturaComputarizadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaResponse FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.validacionRecepcionPaqueteFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest request) {
            return base.Channel.validacionRecepcionPaqueteFacturaComputarizada(request);
        }
        
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaValidacionRecepcionPaqueteDto validacionRecepcionPaqueteFacturaComputarizada(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long codigoRecepcion) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.codigoRecepcion = codigoRecepcion;
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaResponse retVal = ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).validacionRecepcionPaqueteFacturaComputarizada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaResponse> FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.validacionRecepcionPaqueteFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest request) {
            return base.Channel.validacionRecepcionPaqueteFacturaComputarizadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaResponse> validacionRecepcionPaqueteFacturaComputarizadaAsync(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long codigoRecepcion) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.validacionRecepcionPaqueteFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.codigoRecepcion = codigoRecepcion;
            return ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).validacionRecepcionPaqueteFacturaComputarizadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaResponse FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.anulacionFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest request) {
            return base.Channel.anulacionFacturaComputarizada(request);
        }
        
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto anulacionFacturaComputarizada(string codigoSistema, int codigoAmbiente, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long pinAnulacion, long numeroDocumentoFiscal, string cuf, string email, long celular, int codigoMotivo) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.pinAnulacion = pinAnulacion;
            inValue.numeroDocumentoFiscal = numeroDocumentoFiscal;
            inValue.cuf = cuf;
            inValue.email = email;
            inValue.celular = celular;
            inValue.codigoMotivo = codigoMotivo;
            FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaResponse retVal = ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).anulacionFacturaComputarizada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaResponse> FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.anulacionFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest request) {
            return base.Channel.anulacionFacturaComputarizadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaResponse> anulacionFacturaComputarizadaAsync(string codigoSistema, int codigoAmbiente, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, long pinAnulacion, long numeroDocumentoFiscal, string cuf, string email, long celular, int codigoMotivo) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.anulacionFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.pinAnulacion = pinAnulacion;
            inValue.numeroDocumentoFiscal = numeroDocumentoFiscal;
            inValue.cuf = cuf;
            inValue.email = email;
            inValue.celular = celular;
            inValue.codigoMotivo = codigoMotivo;
            return ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).anulacionFacturaComputarizadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionResponse FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.verificarConexion(FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest request) {
            return base.Channel.verificarConexion(request);
        }
        
        public string verificarConexion() {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest();
            FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionResponse retVal = ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).verificarConexion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionResponse> FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.verificarConexionAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest request) {
            return base.Channel.verificarConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionResponse> verificarConexionAsync() {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.verificarConexionRequest();
            return ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).verificarConexionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaResponse FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.recepcionFacturaComputarizada(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest request) {
            return base.Channel.recepcionFacturaComputarizada(request);
        }
        
        public FacturacionSIM.ServiceFacturaComputarizadaStandar.respuestaListaRegistroRecepcionesSoapDto recepcionFacturaComputarizada(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, string fechaEnvio, string archivo) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.fechaEnvio = fechaEnvio;
            inValue.archivo = archivo;
            FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaResponse retVal = ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).recepcionFacturaComputarizada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaResponse> FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController.recepcionFacturaComputarizadaAsync(FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest request) {
            return base.Channel.recepcionFacturaComputarizadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaResponse> recepcionFacturaComputarizadaAsync(string codigoSistema, int codigoAmbiente, int codigoEmision, int codigoModalidad, long nit, string cuis, string cufd, int codigoDocumentoFiscal, int codigoDocumentoSector, int codigoSucursal, long codigoPuntoVenta, string fechaEnvio, string archivo) {
            FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest inValue = new FacturacionSIM.ServiceFacturaComputarizadaStandar.recepcionFacturaComputarizadaRequest();
            inValue.codigoSistema = codigoSistema;
            inValue.codigoAmbiente = codigoAmbiente;
            inValue.codigoEmision = codigoEmision;
            inValue.codigoModalidad = codigoModalidad;
            inValue.nit = nit;
            inValue.cuis = cuis;
            inValue.cufd = cufd;
            inValue.codigoDocumentoFiscal = codigoDocumentoFiscal;
            inValue.codigoDocumentoSector = codigoDocumentoSector;
            inValue.codigoSucursal = codigoSucursal;
            inValue.codigoPuntoVenta = codigoPuntoVenta;
            inValue.fechaEnvio = fechaEnvio;
            inValue.archivo = archivo;
            return ((FacturacionSIM.ServiceFacturaComputarizadaStandar.FacturacionEstandarController)(this)).recepcionFacturaComputarizadaAsync(inValue);
        }
    }
}
