//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionSIM.Models.Data.USER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.UsuaruoIPRestringidoes = new HashSet<UsuaruoIPRestringido>();
            this.Perfils = new HashSet<Perfil>();
            this.Permisoes = new HashSet<Permiso>();
        }
    
        public string UsuarioNombre { get; set; }
        public string UsuarioApellido1 { get; set; }
        public string UsuarioApellido2 { get; set; }
        public string UsuarioEmail { get; set; }
        public string UsuarioTelefono { get; set; }
        public string UsuarioLogin { get; set; }
        public string UsuarioContrasena { get; set; }
        public Nullable<bool> UsuarioHabilitado { get; set; }
        public Nullable<bool> UsuarioEsSuperAdmin { get; set; }
        public Nullable<bool> UsuarioCambiarContrasena { get; set; }
        public int UsuarioID { get; set; }
    
        public virtual ICollection<UsuaruoIPRestringido> UsuaruoIPRestringidoes { get; set; }
        public virtual ICollection<Perfil> Perfils { get; set; }
        public virtual ICollection<Permiso> Permisoes { get; set; }
    }
}
